version: '3'
services:
  mesa_app:
    volumes:
      - "/storage/jenkins/mesa-docker:/home/docker/docker_work:rw"           
          #image: "evbauer/mesa_lean:12778.01"
    build: .
    #ports:
            #- "5000:5000"
       #  mesa_img:
        #image: "evbauer/mesa_lean:12778.01"

